# Generated by Django 2.2.3 on 2019-11-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordertosellers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertosellers',
            name='items',
        ),
        migrations.AddField(
            model_name='ordertosellers',
            name='items_json',
            field=models.CharField(default='hello', max_length=5000),
            preserve_default=False,
        ),
    ]
