# Generated by Django 2.2.3 on 2019-11-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191120_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertosellers',
            name='items_json',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
