# Generated by Django 2.2.6 on 2019-10-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191026_1634'),
        ('orders', '0003_auto_20191001_2259'),
    ]

    operations = [
    ]
