# Generated by Django 2.2.3 on 2019-09-19 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='store_logo',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='99999999999999', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='store_location',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='store_name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
