# Generated by Django 2.2.6 on 2019-10-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190923_1523'),
        ('store', '0003_auto_20190928_0501'),
        ('store', '0004_product_likes'),
    ]

    operations = [
    ]
